input {
  beats {
    port => 5044
  }
}

filter {
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "datn-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
